M48
; DRILL file {KiCad 9.0.1} date 2025-04-09T16:40:48+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-09T16:40:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X59.9Y-96.9
X132.1Y-97.0
X132.1Y-146.1
X132.1Y-169.1
T2
X59.9Y-146.1
X59.9Y-169.1
X117.9Y-146.1
X117.9Y-169.1
M30
